CREATE DATABASE tes;

\c tes

CREATE TABLE IF NOT EXISTS users (
    id   SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

INSERT INTO users (name) VALUES
  ('Alice Johnson'),
  ('Bob Smith'),
  ('Charlie Brown'),
  ('Diana Prince'),
  ('Edward Norton'),
  ('Fiona Green'),
  ('George Harris'),
  ('Hannah Lee'),
  ('Ivan Petrov'),
  ('Julia Roberts'),
  ('Kevin Hart'),
  ('Laura Palmer'),
  ('Michael Scott'),
  ('Natalie Portman'),
  ('Oscar Wilde'),
  ('Patricia Lane'),
  ('Quincy Adams'),
  ('Rachel Green'),
  ('Samuel Jackson'),
  ('Tina Turner'),
  ('Ulysses Grant'),
  ('Victoria Beckham'),
  ('Walter White'),
  ('Xena Warrior'),
  ('Yusuf Islam'),
  ('Zara Ahmed'),
  ('Aaron Burr'),
  ('Bella Swan'),
  ('Carlos Mendez'),
  ('Daisy Miller'),
  ('Ethan Hunt'),
  ('Faith Hill'),
  ('Gary Oldman'),
  ('Holly Golightly'),
  ('Isaac Newton'),
  ('Jasmine Patel'),
  ('Kyle Reese'),
  ('Lily Evans'),
  ('Marcus Aurelius'),
  ('Nina Simone'),
  ('Oliver Twist'),
  ('Penny Lane'),
  ('Quentin Tarantino'),
  ('Rosa Parks'),
  ('Steve Rogers'),
  ('Taylor Swift'),
  ('Uma Thurman'),
  ('Victor Hugo'),
  ('Wendy Williams'),
  ('Xavier Woods'),
  ('Yvonne Strahovski'),
  ('Zachary Taylor'),
  ('Adam Driver'),
  ('Brenda Lee'),
  ('Chris Evans'),
  ('Donna Summer'),
  ('Eli Manning'),
  ('Freya Allan'),
  ('Glen Powell'),
  ('Hana Kim'),
  ('Ian McKellen'),
  ('Jenny Craig'),
  ('Kurt Cobain'),
  ('Luna Lovegood'),
  ('Morgan Freeman'),
  ('Nadia Comăneci'),
  ('Otto Frank'),
  ('Priya Sharma'),
  ('Quinn Hughes'),
  ('Rita Moreno'),
  ('Scott Lang'),
  ('Tara Reid'),
  ('Uri Geller'),
  ('Vanessa James'),
  ('Winston Churchill'),
  ('Xiao Ming'),
  ('Yara Greyjoy'),
  ('Zoe Saldana'),
  ('Alan Turing'),
  ('Bridget Jones'),
  ('Clark Kent'),
  ('Dora Explorer'),
  ('Elvis Presley'),
  ('Frida Kahlo'),
  ('Grace Hopper'),
  ('Harry Potter'),
  ('Indiana Jones'),
  ('James Bond'),
  ('Katniss Everdeen'),
  ('Lara Croft'),
  ('Marie Curie'),
  ('Neo Anderson'),
  ('Ophelia Black'),
  ('Peter Parker'),
  ('Queen Amidala'),
  ('Robin Hood'),
  ('Sherlock Holmes'),
  ('Tony Stark'),
  ('Ursula King');

SELECT COUNT(*) AS total_users FROM users;
SELECT * FROM users LIMIT 5;
